### ISSUE TITLE
Missing build.config.js

### ISSUE THREAD

**Issue by blaketastic2** [thardy/generator-ngbp#13]
I am missing the build.config.js when running generator.

**Comment by blaketastic2** [comment]
It looks like the build.config.js is rolled into the Gruntfile.js. Is this expected, or should it be creating the separate file?

**Comment by thardy** [comment]
It's expected.  I took a thorough sweep through ngbp when making the generator, trying to simplify in as many places as possible.  I eliminated a lot of files, and build.config.js was one of them.  I think the main things in there were the app files variable and perhaps the list of vendor files, which are now near the top of Gruntfile.js.
