### ISSUE TITLE
It would be nice if sub-modules would be created correctly

### ISSUE THREAD

**Issue by FDIM** [thardy/generator-ngbp#15]
Hi,
This is a quite good way to start creating ngbp app and I would like to propose a change to module generator.
It would be great if a sub-modules would be supported (a module in a module). 

That is if module name is 'user.profile':
* a user.profile module should be created in {app}/user folder, not just {app}
* file names should start with 'profile' and not "user.profile"
* controller and module js files requires no changes.
 
I can try and make the changes and create a PR if you agree with this.

**Comment by thardy** [comment]
This sounds good.  So, you're just talking about a modification to the existing module when they use a module name with a dot in it?  The only thing I'd add is a confirmation (can default to yes) that they are about to create a module within a module.  That way, they could still create a module with a dot in the name if that was their intention.

**Comment by FDIM** [comment]
Yep, this is exactly what I am talking about. Glad that you agree.
I think I'll have a look at the code in the weekend and create a PR if that is ok with you.

**Comment by thardy** [comment]
I merged this today.  Fixed one issue.  See comments in pull request.
