### ISSUE TITLE
please sync Gruntfile with original ngpb

### ISSUE THREAD

**Issue by karser** [thardy/generator-ngbp#18]
This PR is not included https://github.com/ngbp/ngbp/commit/67739b8bd9d9a19bdae6f830da3e134d89ab2735

**Comment by thardy** [comment]
I'll get that in soon.  I'm thinking about trying out kevinbuffington's solution instead of the PR, if it will accomplish the same thing.

**Comment by deviantony** [comment]
:+1:

**Comment by thardy** [comment]
I used kevinbuffington's solution.  Please check it out and make sure it's doing everything you expect it to.
